#####...######..#####...##..##...####...#####
##..##....##....##..##..##..##..##..##..##..##
#####.....##....##..##..######..######..#####
##..##....##....##..##..##..##..##..##..##..##
##..##..######..#####...##..##..##..##..#####

name = "contact_form_api"
main = "src/index.js"
compatibility_date = "2023-07-11"

[vars]
WEBHOOK_URL=""